## COMP2006: Graded Lab 2

In this lab, you will create a *k-nearest neighbours* algorithm from scratch. 

**Requirements**

- All code written in Python
- Create a Python class called `KNeighbours` that:
    - (10 marks) initializes an instance of the class with a user-provided value of `k` and whether or not it will be used for a *regression* or a *classification* problem
    - (15 marks) contains a method to calculate the Euclidean distance between a test point and all points in a training data set
        - do NOT use built-in functions to calculate the distance
    - (15 marks) contains a method that sorts Euclidean distances and returns the top-`k` values and the indices of those samples in the training data set
    - contains a prediction method for:
        - (15 marks) classification
        - (15 marks) regression
- (15 marks) Use sklearn's `make_classification()` function to generate data and test if your class works
    - compare the results of your class to those of sklearn's `KNeighborsClassifier`
- (15 marks) Use sklearn's `make_regression()` function to generate data and test if your class works
    - compare the results of your class to those of sklearn's `KNeighborsRegressor`

**What to submit**
 - A completed copy of this notebook with all final, error-free code executed and all output visible in the notebook
 - ONE submission per group

## **The KNeighbours class - TEAM 7**

**Manuel Bishop Noriega - 4362207**

**Robert Matney - 4364229**

we added 2 more methods, fit and predict. just to replicate the way sklearn.neighbors are used. we could have only called predictors methods passing them all training datasets and test point directly. 

In [123]:
# import numpy as np
# import matplotlib.pyplot as plt
# import pandas as pd

from math import sqrt # had to use this builtin function :(
class KNeighbours:
    
# default constructor to take k and type of model to use
    def __init__(self,k,model_type="regressor"):
        self.k=k
        self.distances=[]
        self.X_train=[]
        self.y_train=[]
        if model_type=="regressor" or model_type=="classifier":
            self.model_type=model_type
        else:
            self.model_type="regressor"
            print(f'using default model regression')


# calculates distances between testpoint and all points in tain data set
    def calculate_euclidean_distance(self, test, train_points):
        idx=0
        self.distances=[]
        for trp in train_points:
            dist=abs(sqrt(abs(test[0]-trp[0])**2 + abs(test[1]-trp[1])**2))
            self.distances.append([idx,dist])
            idx+=1
        return self.distances

# sorts the distances and returns the top-k values    
    def sort_distances(self):
        sorted_distances=sorted(self.distances,key=lambda pt:pt[1])
        k_distances=[]
        for i in range(0,self.k):
            k_distances.append(sorted_distances[i])
        return k_distances

# I created this method feeds class object with training data
# receives 2 training data sets: X for features and y for targets
    def fit(self, X_train, y_train):
        self.X_train=X_train
        self.y_train=y_train

# Method to deliver prediction according to parameter model_type during instantiation
# similar to sklearn.neighbors, takes a point to make its prediction
    def predict(self,test):
        result=None
        if self.model_type=="regressor":
            result=self.myRegressor(test)
        else:
            self.model_type=="classifier"
            result=self.myClassifier(test)
        return result

# method for classification prediction method
# receives a testint point, looks for k nearest neighbors in the training data
# and then check their classes, predicts according to the class with most incidences.
    def myClassifier(self,test):
        self.calculate_euclidean_distance(test,self.X_train)
        knn=self.sort_distances()
        class0=0
        class1=0
        predict=None
        for i in knn:
            if self.y_train[i[0]]==0:
                class0+=1
            else:
                class1+=1
        if class0>class1:
            predict=0
        else:
            predict=1
        #print(f'point {test} belongs to class {predict}')
        return predict

# method for regression prediction method
# receives a testint point, looks for k nearest neighbors in the training data
# and then calculates the average value, returns this value as prediction
    def myRegressor(self, test):
        self.calculate_euclidean_distance(test,self.X_train)
        knn=self.sort_distances()
        predict=None
        for i in knn:
            if predict is None:
                predict=0
            predict+=self.y_train[i[0]]
        predict=predict/self.k
        #print(f'predicted value is: {predict}')
        return predict


## Regression models comparisson
**Creating regression training data sets and test point**

In [124]:
from sklearn.datasets import make_regression
#data set for regression method
X,y = make_regression(n_samples = 1000, n_features = 2, random_state = 16)
#testing point
test=[0,0]

** Showing Training features and target arrays **

In [125]:
X,y

(array([[ 0.04927378, -0.05732992],
        [-0.33573971, -0.07907426],
        [-1.00185   ,  0.11094109],
        ...,
        [ 2.1329826 ,  0.327569  ],
        [ 0.13775994, -0.37768519],
        [-0.36391213,  1.01362424]]),
 array([-1.15453814e+00, -1.72427327e+01, -3.29079797e+01, -2.66345386e+01,
         1.95204258e-01,  3.71579884e+01,  4.49270057e+01, -2.27578400e+01,
         7.95395525e+01, -1.24506519e+01,  5.10366960e+01, -6.43227587e+01,
         1.70961209e+02,  8.11845180e+01, -2.54342399e+01,  1.02177552e+02,
         1.76640245e+01, -4.81849674e+01, -1.82789586e+01, -5.50151382e+01,
        -5.53125020e+00, -1.45817044e+01, -3.12823755e+01,  2.93865501e+00,
         2.18681274e+01,  1.65756540e+01, -4.37936558e+01, -8.72608084e+01,
         4.90590842e+01,  3.79094498e+01,  5.75268197e+01, -2.48796536e+01,
         2.19246885e+01, -2.81225565e+01, -6.79820299e+00, -5.24418118e+01,
        -8.85558773e+01, -3.20477349e+00,  6.01119603e+01,  4.83091640e+01,
         

**Training my model**

In [126]:

k=3
# Instantiating KNeighbours object as regressor
myreg=KNeighbours(k,"regressor")

#training with regression data set
myreg.fit(X,y)


**looking at the distances array and kNN distances array**

Just calling distance methods to show what they return, not really needed to call them separatedly because they are callled when predict method is called

In [127]:
# distances between train points and test point array
print(f"distances array : {myreg.calculate_euclidean_distance(test,X)}")
# kNN distances sorted array
print(f"\nkNN distances sorted array : {myreg.sort_distances()}")

distances array : [[0, 0.07559514115918975], [1, 0.34492592236435604], [2, 1.0079738810519359], [3, 0.4120717509860601], [4, 0.6692272228920918], [5, 0.5862676028367213], [6, 0.7585782763741025], [7, 0.8139982434306787], [8, 1.2077804117148108], [9, 0.3803442494256011], [10, 1.0247346684080139], [11, 1.8230821150788996], [12, 2.5892534732637844], [13, 1.3548960045482517], [14, 1.0491190884545982], [15, 1.7539215044816763], [16, 1.7825993194661827], [17, 0.8667387288982338], [18, 0.5362308161990428], [19, 0.9993712410770464], [20, 0.5769300989435819], [21, 0.9538254428175145], [22, 2.077750640811474], [23, 0.049643793002944005], [24, 1.7437493754625597], [25, 1.062916670505646], [26, 0.9625219663349494], [27, 1.3328517691160153], [28, 0.9374089897448472], [29, 0.6934618747208786], [30, 0.9675263917218935], [31, 1.2757743699928703], [32, 0.5362258611112384], [33, 0.6984573144297498], [34, 0.2995206554223268], [35, 0.984660054110219], [36, 2.2145519446811117], [37, 0.09954854550450686], [

**Training sklearn model, predicting with both models and comparing results**

In [128]:

#predicting value for test point
print(f"my regressor prediction for: {test}")
print(f"predicted value is: {myreg.predict(test)}")

#importing sklearn regressor
from sklearn.neighbors import KNeighborsRegressor
# instantiating regressor
reg = KNeighborsRegressor(n_neighbors=k)

# training model with regression data set
reg.fit(X,y)
#printing sklear prediction
print("\nsklearn regressor prediction for: " + str(test))
result=reg.predict([test])
print(f"predicted value is: {result[0]}")


my regressor prediction for: [0, 0]
predicted value is: 2.181735091500633

sklearn regressor prediction for: [0, 0]
predicted value is: 2.181735091500633


## Classification models comparisson
**Creating classification training data sets and test point**

In [129]:
from sklearn.datasets import make_classification
#data set for classification method
X1,y1 = make_classification(n_samples = 100, n_features = 2, n_redundant = 0, random_state = 57)
#testing point
test=[0,0]

** Showing Training features and target arrays **

In [130]:
X1,y1

(array([[ 0.91295449,  0.67988944],
        [-0.2110705 , -1.22756822],
        [-0.58673807,  1.12954582],
        [-0.66379395,  0.46264767],
        [-1.24551309,  0.40602359],
        [-0.99292103,  0.93884851],
        [ 0.69279482, -0.66748838],
        [-1.41760126,  0.29610977],
        [ 0.796899  ,  0.51601826],
        [ 0.97699194,  1.12253701],
        [ 2.27575057, -1.65471782],
        [-1.0206412 ,  0.89914856],
        [ 0.27516389,  0.68036392],
        [-2.29966723,  1.81053531],
        [-0.9524843 , -0.63980945],
        [ 1.1521143 , -0.74055519],
        [ 0.34608866, -0.69641285],
        [-1.7008346 ,  0.16001261],
        [ 0.65912736,  0.89294899],
        [ 1.14624208,  2.00093983],
        [ 1.18618565,  2.6546222 ],
        [-0.18049486, -0.82883363],
        [ 0.12441637, -0.93833734],
        [ 0.5019167 ,  0.8862587 ],
        [ 3.90869522, -2.42777445],
        [-1.07435979,  1.52390747],
        [-0.46845316, -0.98191025],
        [-1.95284984,  0.520

**Training models and printing their results to compare**

In [131]:
k=3
# Instantiating KNeighbours object as classifier
myclf=KNeighbours(k,"classifier")
#training with classification data set
myclf.fit(X1,y1)
#predicting class for test point
print(f"my classifier prediction for: {test}")
print(f"point {test} belongs to class {myclf.predict(test)}")


#importing class
from sklearn.neighbors import KNeighborsClassifier
# instantiating classifier
clf = KNeighborsClassifier(n_neighbors=k) #<-- el parámetro es k vecinos cercanos

# training model with classification data set
clf.fit(X1, y1)

# printing sklear prediction
print(f"\nsklearn classifier prediction for {test}")
#result=clf.predict([test])
#print(f"point {test} belongs to class {result[0]}")
print(f"point {test} belongs to class {clf.predict([test])}")


my classifier prediction for: [0, 0]
point [0, 0] belongs to class 1

sklearn classifier prediction for [0, 0]
point [0, 0] belongs to class [1]
